version: '3.8'
services:
  micro-job:
    container_name: micro-job
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    environment:
      - VIRTUAL_HOST=job-api.siesco.studio
      - VIRTUAL_PORT=80
    networks:
      - public-network
networks:
  public-network:
    external: true
