version: '3.8'
services:
  reporto-draft:
    container_name: micro-job
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    environment:
      - VIRTUAL_HOST=microjob.az
      - VIRTUAL_PORT=80
    networks:
      - job-network
networks:
  job-network:
    external: true
