version: '3.8'
services:
  gateway:
    container_name: job-gateway
    build:
      context: .
      dockerfile: Gateway/Job.Gateway/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - auth
      - jobuser
      - jobcompany
      - jobpayment
    environment:
      - VIRTUAL_HOST=job-api.siesco.studio
      - VIRTUAL_PORT=8080
    networks:
      - public-network

  auth:
    container_name: job-auth-service
    build:
      context: .
      dockerfile: src/Services/Authentication/AuthService.API/Dockerfile
    ports:
      - "5002:8080"
    networks:
      - public-network

  jobuser:
    container_name: jobuser-service
    build:
      context: .
      dockerfile: src/Services/Job/JobUser/Job.API/Dockerfile
    ports:
      - "5003:8080"
    networks:
      - public-network
    volumes:
      - hiri_wwwroot_data:/app/wwwroot  
      
  jobcompany:
    container_name: jobcompany-service
    build:
      context: .
      dockerfile: src/Services/Job/JobCompany/JobCompany.API/Dockerfile
    ports:
      - "5004:8080"
    networks:
      - public-network
    volumes:
      - hiri_wwwroot_data:/app/wwwroot 
      
  jobpayment:
    container_name: jobpayment-service
    build:
      context: .
      dockerfile: src/Services/JobPayment/JobPayment.API/Dockerfile
    ports:
      - "5016:8080"
    networks:
      - public-network
networks:
  public-network:
    external: true
